Bugfix 282 image picker autocomplete
Metatavu/mantyharju-wp-theme pull request #283
Opened 2021-12-31 14:41 UTC by Chi-Chu319

resolves #282

2022-01-14 12:42 UTC, lauriLukkarinen requested changes

2022-01-14 12:42 UTC, lauriLukkarinen commented on src/components/pages/WelcomePage.tsx
> +          renderInput={(params) =>
```suggestion
          renderInput={ params =>
```

2022-01-14 12:42 UTC, lauriLukkarinen commented on src/components/pages/WelcomePage.tsx
> +              InputProps={{ ...params.InputProps }}
```suggestion
              InputProps={{ ...params.InputProps }}
              { ...params }
```

2022-01-14 12:42 UTC, lauriLukkarinen commented on src/components/pages/WelcomePage.tsx
> +
```suggestion
    this.setState({ autocompleteInput: newInputValue });
```

2022-01-14 12:42 UTC, lauriLukkarinen commented on src/components/pages/WelcomePage.tsx
> +    });
```suggestion
    this.setState({ autocompleteValue: value || undefined });
```

2022-01-14 12:42 UTC, lauriLukkarinen commented on src/components/pages/WelcomePage.tsx
> +    })
```suggestion
    this.setState({ autocompleteOptions: autocompleteOptions })
```

2022-01-14 12:42 UTC, lauriLukkarinen commented on src/components/pages/image-picker.tsx
> +export default withStyles(styles)(ImagePicker)
```suggestion
export default withStyles(styles)(ImagePicker);
```

2022-01-14 12:42 UTC, lauriLukkarinen commented on src/components/pages/image-picker.tsx
> +  public render = () => {
```suggestion
  /**
   * Component render method
   */
  public render = () => {
```

2022-01-14 12:42 UTC, lauriLukkarinen commented on src/components/pages/image-picker.tsx
> +  private renderImage = (image: Image, onImagePick: () => void) => {
```suggestion
  /**
   * Renders image
   *
   * @param image image
   * @param onImagePick on image pick event handler
   */
  private renderImage = (image: Image, onImagePick: () => void) => {
```

2022-01-14 12:42 UTC, lauriLukkarinen commented on src/components/pages/image-picker.tsx
> +class ImagePicker extends React.Component<Props> {
```suggestion
/**
 * Image picker component
 */
class ImagePicker extends React.Component<Props> {
```

2022-01-14 12:42 UTC, lauriLukkarinen commented on src/components/pages/image-picker.tsx
> +interface Props extends WithStyles<typeof styles> {
```suggestion
/**
 * Component properties
 */
interface Props extends WithStyles<typeof styles> {
```

2022-01-14 12:42 UTC, lauriLukkarinen commented on src/components/pages/image-picker.tsx
> +    );
```suggestion
    return (
      <div className={ classNames(classes.imagePickerResponsive, image.selected && classes.imagePickerResponsiveSelected) }
        onClick={ onImagePick }>
        <img
          src={ image.src }
          className={ classNames(classes.imagePickerResponsiveThumbnail, image.selected && classes.imagePickerSelected) }
          style={{ width: 150, height: 150, objectFit: "cover" }}
        />
      </div>
    );
```

2022-01-17 09:35 UTC, Chi-Chu319 commented on src/components/pages/image-picker.tsx
> +   */
```suggestion
  /**
   * Component render method
   */
```

2022-01-17 09:36 UTC, Chi-Chu319 reviewed
removed duplicated

2022-01-17 13:26 UTC, lauriLukkarinen requested changes

2022-01-17 13:26 UTC, lauriLukkarinen commented on src/components/pages/WelcomePage.tsx
> +              images={ imageList.map((image, i) => ({src: image, value: i, selected: defaultImageUrl === image})) }
```suggestion
              images={ imageList.map((image, i) => ({ src: image, value: i, selected: defaultImageUrl === image })) }
```

2022-01-17 13:26 UTC, lauriLukkarinen commented on src/components/pages/image-picker.tsx
> +    super(props)
```suggestion
    super(props);
```

2022-01-17 13:26 UTC, lauriLukkarinen commented on src/components/pages/image-picker.tsx
> +      <div className={ classNames(classes.imagePickerResponsive, image.selected && classes.imagePickerResponsiveSelected) }
```suggestion
      <div className={ classNames(classes.imagePickerResponsive, { [classes.imagePickerResponsiveSelected]: image.selected }) }
```

2022-01-17 13:26 UTC, lauriLukkarinen commented on src/components/pages/image-picker.tsx
> +          className={ classNames(classes.imagePickerResponsiveThumbnail, image.selected && classes.imagePickerSelected) }
```suggestion
          className={ classNames(classes.imagePickerResponsiveThumbnail, { [classes.imagePickerSelected]: image.selected }) }
```

2022-01-17 13:33 UTC, lauriLukkarinen approved these changes

2022-01-17 13:33 UTC, merged