It worked before, now styles need to be fixed after PR #48
Metatavu/mantyharju-wp-theme pull request #51
Opened 2020-08-24 13:15 UTC by Daniilmass

resolves #50

2020-08-24 19:38 UTC, Kaemppi commented on src/styles/single-event-page.ts
> +    height:"20vw",
Just curious: why vw unit? It is a relative unit to viewport width and can cause some strange behaviour specially when used as heights. Unit vh is preferred in heights which is the same, but relative to viewport height.

2020-08-25 12:20 UTC, terolamminpaa requested changes

2020-08-25 12:20 UTC, terolamminpaa commented on linkedevents/events.php
> +    $siteUrlBase = "http://localhost/";
There is a way to get this information from wordpress database using a function so it doesn't need to be hardcoded.
Maybe one of these?
[site url](https://developer.wordpress.org/reference/functions/site_url/)
[home url](https://developer.wordpress.org/reference/functions/get_home_url/)

2020-08-25 12:20 UTC, terolamminpaa commented on src/components/pages/SingleEventPage.tsx
> + * A component for basic layout footer contents
Update tsdocs

2020-08-25 12:20 UTC, terolamminpaa commented on src/components/pages/SingleEventPage.tsx
> +                <Link color="inherit" href="/" onClick={() => {}}>
if the onClick handler isn't mandatory here then we could remove it

2020-08-28 08:48 UTC, Daniilmass commented
PR to be closed as it has been moved to #67 one to avoid conflicts

2020-08-28 08:48 UTC, Daniilmass commented
PR to be closed as it has been moved to #67 one to avoid conflicts

2020-08-28 08:48 UTC, closed without merging